apiVersion: ac3.redhat.com/v1alpha1
kind: Link
metadata:
  name: test-link
  namespace: sk1
spec:
  sourceCluster: "ac3-cluster-2"
  targetCluster: "ac3-cluster-1"
  sourceNamespace: "sk1"
  targetNamespace: "test-skupper"
  secretNamespace: "sk1"
  secretName: "sk1-token"
  secretName2: "sk1-token"
  port: 5672

